[package]
name = "happiny"
version = "0.3.1"
edition = "2021"

[dependencies]
gtk = "0.18.1"
serde_json = "1.0.116"
async-channel = "2.2.1"

[dependencies.serde]
version = "1.0.199"
features = ["derive"]