[package]
name = "happiny"
version = "0.1.0"
edition = "2021"

[dependencies]
gtk = "0.14.0"
serde_json = "1.0.72"
css-color-parser2 = "1.0.1"

[dependencies.serde]
version = "1.0.131"
features = ["derive"]